### ISSUE TITLE
Support command-line equivalent

### ISSUE THREAD

**Issue by skjolber** [entur/owasp-orb#5]
Dependency-check also has a command-line variant: https://jeremylong.github.io/DependencyCheck/dependency-check-cli/index.html

Support download of the latest version and running a scan; caching both the executable itself and data directory. Get latest executable doing something like

```
# Inspired by https://hub.docker.com/r/owasp/dependency-check/dockerfile
name: Install Owasp dependency check
working_directory: ~/
environment:
  OWASP_VERSION_URL: 'https://jeremylong.github.io/DependencyCheck/current.txt'
  OWASP_DOWNLOAD_URL: 'https://dl.bintray.com/jeremy-long/owasp'
command: |
  version=$(curl --silent $OWASP_VERSION_URL)
  wget -O owasp.zip "$OWASP_DOWNLOAD_URL/dependency-check-${version}-release.zip"
  unzip owasp.zip

```
